language: java

jdk:
  - openjdk7

sudo: false

before_install:
  - ls -a
  - pwd
  - ./gradlew clean

env:
  global:
  - civbuddy_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac
  - civbuddy_jdk6_javadoc=/usr/lib/jvm/java-6-openjdk-amd64/bin/javadoc

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
