name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI: true
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '8'
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run build
            - run: npm test
            - run: npm run prod
